server:
  port: 8080
#  context-path: /Girl

girl:
  cupSize: B
  age: 18

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/sampledb
    username: root
    password: 123456
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true



#content: "cupSize: ${cupSize},age: ${age}"

#prot: 后加空格

#server.port=8080
#server.context-path=/Girl




#
#spring.datasource.url=jdbc:mysql://127.0.0.1:3306/
#spring.datasource.username=admin
#spring.datasource.password=123456
#spring.datasource.driver-class-name=com.mysql.jdbc.Driver